# Generated by Django 3.1.3 on 2023-03-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.CharField(default='default content', max_length=500),
        ),
    ]
