# Generated by Django 3.1.3 on 2023-03-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='Default Value'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.TextField(default='Default Value'),
        ),
    ]
